### ISSUE TITLE
[feature request] server auto-start on join

### ISSUE THREAD

**Issue by ElliotS2007** [exaroton/exaroton-velocity#1]
Make it so when a person joins the proxy (fx. One that’s always running) it automatically starts a specified server. So you could have a proxy witch is always running and then have a backend server that only starts when people actually want to join them.

**Comment by JulianVennen** [comment]
Why don't you just let the proxy go offline?
You can automatically let it start when someone tries to join, and it can then also start your backend servers using the plugin.

**Comment by ElliotS2007** [comment]
Yes, but what if you have people online on one back end and none on some others, then there's no reason to run the others. But let's say that the people online want to go to survival, and it's offline, it would be cool if it then started when you join. It would save so much credit.

**Comment by JulianVennen** [comment]
You can already use the /exaroton start command to start the survival server in that case

**Comment by ElliotS2007** [comment]
Yes, but that would require user knowledge and permission or you would need an admin only 24/7

**Comment by JulianVennen** [comment]
I'm not sure how switching to a different server requires less knowledge than starting a server and then switching to it.
You can also only give the start permission specifically.

**Comment by ElliotS2007** [comment]
Well, okay yes, but that still requires the people playing to know the command.

**Comment by JulianVennen** [comment]
The new switch command probably fits your idea
